Feature forgot password
WildCodeSchool/2104-wns-remote-tsleague pull request #30
Opened 2021-12-08 09:37 UTC by lucas240

2021-12-08 13:37 UTC, AuxB requested changes

2021-12-08 13:37 UTC, AuxB commented on client/src/components/ForgotPassword/ForgotPassword.tsx
> +              : 'PixeLearn - Chagner de mot de passe'}
Faute de frappe sur "Changer"

2021-12-08 13:37 UTC, AuxB commented on client/src/components/Router.tsx
> +      pathname !== '/register-student' &&
A l'avenir mettre une regex pour éviter l'ajout de ligne

2021-12-08 13:37 UTC, AuxB commented on server/src/resolvers/users-resolver.ts
>    public async createUser(@Arg('input') userInput: UserInput) {
Ca on va pouvoir le supprimer je pense, mais pour une prochaine refacto

2021-12-08 13:37 UTC, AuxB commented on server/src/resolvers/validator/userInput.ts
>  import { InputType, Field } from 'type-graphql';
Normalement on a un dossier types pour mettre les types côté back

2021-12-08 13:37 UTC, AuxB commented on server/src/utils/mailing/send.ts
> +    to: data.mail,
Pourquoi avoir mis data ? C'est bien plus clair et moins error prone de destructuer l'objet

2021-12-08 13:50 UTC, lucas240 commented on client/src/components/Router.tsx
> +      pathname !== '/register-student' &&
j'ai essayé de mette une regex mais je n'ai pas réussi, et j'ai remarqué que c'est plus facile de changer le code avec l'ajout de ligne qu'avec une regex

2021-12-09 12:57 UTC, AuxB approved these changes
Bon pour moi, good job !

2021-12-09 13:02 UTC, JonathanArnould approved these changes
Ok, good!

2021-12-09 13:03 UTC, merged